# ========================================================
# WinPE WireGuard Bare-Metal Network Configuration
# ========================================================

# Global Defaults
Adapter=Ethernet0
Default_Mask=255.255.255.0
Default_Gateway=<IP>

# Central / Concentrator Endpoints
Tunnel=<IP>
Backup=<IP>

# Server 1
SRV1_Name=<Name>
SRV1_IP=<IP>
SRV1_Mask=<empty or different from default>
SRV1_Gateway=<IP>
SRV1_Config=<WireGuard config file>

# Server 2
SRV2_Name=<Name>
SRV2_IP=<IP>
SRV2_Mask=<empty or different from default>
SRV2_Gateway=<IP>
SRV2_Config=<WireGuard config file>

# Server 3
SRV3_Name=<Name>
SRV3_IP=<IP>
SRV3_Mask=<empty or different from default>
SRV3_Gateway=<IP>
SRV3_Config=<WireGuard config file>
