Adapter=Ethernet0
Mask=255.255.255.0
Gateway=<IP>
Tunnel=<IP>
Backup=<IP>

SRV1_Name=<Name>
SRV1_IP=<IP>
SRV1_Config=<WireGuard config file>

SRV2_Name=<Name>
SRV2_IP=<IP>
SRV2_Config=<WireGuard config file>

SRV3_Name=<Name>
SRV3_IP=<IP>
SRV3_Config=<WireGuard config file>
