# =========================================================
# WireGuard Client Profile Template for Physical WinPE Host
# =========================================================

[Interface]
# Generated client private key for this physical machine
PrivateKey = <this device base64 key>

# Assigned WireGuard tunnel IP from the Concentrator pool
Address = <IP of WireGuard tunnel>/32

[Peer]
# Concentrator (pfSense-WG OPT2) Public Key
PublicKey = <destination base64 key>

# pfSense-WG internal Customer_Internal (WAN) IP and port 51820
Endpoint = <IP>:51820

# Allowed traffic through the tunnel: Carrier LAN, Concentrator Pool, and Rubrik Network
AllowedIPs = <list of IPs and subnets allowed>

# Hardened v2 keepalive
PersistentKeepalive = 15
