# ========================================================
# WireGuard Client Profile Template for Physical WinPE Host
# ========================================================

[Interface]
PrivateKey = <this device base64 key>
Address = <IP of WireGuard tunnel>/32

[Peer]
PublicKey = <destination base64 key>
Endpoint = <IP>:<port>
AllowedIPs = <list of IPs and subnets allowed>
PersistentKeepalive = 20
