[Interface]
PrivateKey = <this device base64 key>
Address = 100.64.6.130/32

[Peer]
PublicKey = <destination base64 key>
Endpoint = <IP>:<port>
AllowedIPs = <list of IPs and subnets allowed>
PersistentKeepalive = 25
